#!/usr/bin/perl -w
my $top=qq@<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>romfs files</title>
<style type="text/css">
<!--
body { text-align: left }
img { border: 0px; vertical-align: middle }
hr { width: 70%; margin-left: auto; margin-right: auto; text-align: center }
h1 { font-size: larger }
.none { display: none }
.center { text-align: center; margin-left: auto; margin-right: auto }
-->
</style>
</head>
@;

my @revs=("0.5.1:2002-01-22","0.5:2002-01-20","0.3:1998-09-22");
my %files = (
  "0.5.1" => ["genromfs-0.5.1.tar.gz"],
  "0.5" => ["genromfs-0.5.tar.gz"],
  "0.3" => ["genromfs-0.3.tar.gz"],
);
my %hashes = (
  "genromfs-0.5.1.tar.gz" => "fee69ecbf8f990fdb0ca0c7267c13e7e:20k",
  "genromfs-0.5.tar.gz" => "d89a41211b4a43e2d0c5826c2a6201e3:20k",
  "genromfs-0.3.tar.gz" => "1b7e1adf1123395e34f7e6a37801b38c",
);
my %proto = (
  "10:HTTP:(SourceForge):0.5:0.5.1"=>"http://prdownloads.sourceforge.net/romfs/",
  "01:HTTP:ACOMP:0.5:0.5.1"=>"http://www.acomp.hu/romfs/files/",
  "02:HTTP:ibiblio:0.5.1"=>"http://www.ibiblio.org/pub/Linux/system/recovery/",
  "05:HTTP:Telia/SF:0.5:0.5.1"=>"http://telia.dl.sourceforge.net/romfs/",
  "05:HTTP:Cesnet/SF:0.5:0.5.1"=>"http://cesnet.dl.sourceforge.net/romfs/",
  "10:FTP:SourceForge:0.5:0.5.1"=>"ftp://ftp1.sourceforge.net/pub/sourceforge/romfs/",
# "11:FTP:Banki"=>"ftp://ftp.banki.hu/pub/Linux/local/",
  "12:FTP:ibiblio:0.5.1"=>"ftp://ftp.ibiblio.org/pub/Linux/system/recovery/",
);

print $top;
print "<body>\n";

print qq|
<p>
List of <em>romfs</em> related files follows below
(currently only various versions of genromfs).
This is free software, available under the terms of the
<a href="http://www.gnu.org/copyleft/gpl.html">GNU General Public License</a>.
</p>
|;

print "<ul>\n";
for my $k (@revs) {
  my ($v,$d)=split(/:/,$k);
  print "<li>release $v ($d)\n";
  print "  <ul>\n";
  for my $f (@{$files{$v}}) {
    my $h = $hashes{$f};
    my ($md5,$size)=split(/:/,$h);
    print "  <li>$f";
    my (@attrs)=();
    if ($size) { push @attrs,"$size" }
    if ($md5) { push @attrs,"MD5: $md5" }
    if (@attrs) { print " (".join(", ",@attrs).")"; }
    print "\n";
    print "  <ul>\n";
    my %all=();
    for my $p (sort keys %proto) {
      # XXX: split
      my ($line,$scheme,$site,$vonly)=split(/:/,$p,4);
      if (!$vonly || ":$vonly:" =~ /:$v:/) {
        $url=$proto{$p}.$f;
        $all{$scheme} .= "<a href=\"$url\">$site</a>\n";
      }
    }
    my $found=0;
    for my $p (sort keys %proto) {
      my ($line,$scheme,$site)=split(/:/,$p);
      if ($all{$scheme}) {
        $found++;
        print "  <li> via $scheme\n$all{$scheme}</li>\n";
        delete $all{$scheme};
      }
    }
    print "    <li>(no live mirror found)</li>\n" unless $found;
    print "  </ul>\n";
    print "  </li>\n";
  }
  print "  </ul>\n";
  print "</li>\n";
}
print "</ul>\n";

print "<hr />\n";

print qq@<p class="center">
files
<span class="none"> | Powered by </span>
<a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=2320" width="88" height="31" alt="SourceForge" /></a>
<span class="none"> | </span>
<a href="http://validator.w3.org/check/referer"><img src="http://www.w3.org/Icons/valid-xhtml10" height="31" width="88" alt="Valid XHTML 1.0!" /></a>
<br />
@;
print "\$"."Date\$\n";
print "<span class=\"none\"> | ";
print "\$"."Revision\$ </span>\n";

print qq@<br />
<a href="http://www.google.com">Google</a> *
<a href="http://anti-dmca.org/">DMCA</a> *
<a href="http://www.xenu.net/">Scientology</a> *
<a href="http://www.xenu.net/">Dianetics</a> *
<a href="http://www.koan19.net/">koan19.net</a> =
<a href="http://www.koan19.org/">koan19.org</a> =
<a href="http://www.koan19.com/">koan19.com</a> =
</p>

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-317553-4";
urchinTracker();
</script>

</body>
</html>
@;
