#!/usr/bin/perl -w
my $top=qq@<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>romfs files</title>
<style type="text/css">
<!--
body { text-align: left }
img { border: 0px; vertical-align: middle }
hr { width: 70%; margin-left: auto; margin-right: auto; text-align: center }
h1 { font-size: larger }
.none { display: none }
.center { text-align: center; margin-left: auto; margin-right: auto }
-->
</style>
</head>
@;

my @revs=("0.5.1:2002-01-22","0.5:2002-01-20");
my %files = (
  "0.5.1" => ["genromfs-0.5.1.tar.gz"],
  "0.5" => ["genromfs-0.5.tar.gz"],
);
my %hashes = (
  "genromfs-0.5.1.tar.gz" => "fee69ecbf8f990fdb0ca0c7267c13e7e",
  "genromfs-0.5.tar.gz" => "d89a41211b4a43e2d0c5826c2a6201e3",
);
my %proto = (
  "00:HTTP:SourceForge"=>"http://prdownloads.sourceforge.net/romfs/",
  "01:HTTP:ACOMP"=>"http://www.acomp.hu/romfs/files/",
  "05:HTTP:Telia/SF"=>"http://telia.dl.sourceforge.net/romfs/",
  "10:FTP:SourceForge"=>"ftp://ftp1.sourceforge.net/pub/sourceforge/romfs/",
  "11:FTP:Banki"=>"ftp://ftp.banki.hu/pub/Linux/local/",
  "12:FTP:ibiblio:0.5.1"=>"ftp://ftp.ibiblio.org/pub/Linux/system/recovery/",
);

print $top;
print "<body>\n";

print "<ul>\n";
for my $k (@revs) {
  my ($v,$d)=split(/:/,$k);
  print "<li>release $v ($d)\n";
  print "  <ul>\n";
  for my $f (@{$files{$v}}) {
    my $h = $hashes{$f};
    print "  <li>$f (MD5: $h)\n";
    print "  <ul>\n";
    my %all=();
    for my $p (sort keys %proto) {
      # XXX: split
      my ($line,$scheme,$site,$vonly)=split(/:/,$p);
      if (!$vonly || $vonly eq $v) {
        $url=$proto{$p}.$f;
        $all{$scheme} .= " <a href=\"$url\">$site</a>";
      }
    }
    for my $p (sort keys %proto) {
      my ($line,$scheme,$site)=split(/:/,$p);
      if ($all{$scheme}) {
        print "  <li> via $scheme$all{$scheme}</li>\n";
        delete $all{$scheme};
      }
    }
    print "  </ul>\n";
    print "  </li>\n";
  }
  print "  </ul>\n";
  print "</li>\n";
}
print "</ul>\n";

print "<hr />\n";

print qq@<p class="center">
files
<span class="none"> | Powered by </span>
<a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=2320" width="88" height="31" alt="SourceForge" /></a>
<span class="none"> | </span>
<a href="http://validator.w3.org/check/referer"><img src="http://www.w3.org/Icons/valid-xhtml10" height="31" width="88" alt="Valid XHTML 1.0!" /></a>
<br />
@;
print "\$"."Date\$\n";
print "<span class=\"none\"> | ";
print "\$"."Revision\$ </span>\n";
print "</p>\n";

print "</body>\n";
print "</html>\n";
